[network]
network = "Mainnet"
listen_addr = "0.0.0.0:8233"

[state]
cache_dir = "/home/zebra/.cache/zebra"

[rpc]
listen_addr = "0.0.0.0:8232"
parallel_cpu_threads = 4

[tracing]
filter = "info"

[metrics]
endpoint_addr = "0.0.0.0:9999"
