/**
 * The v6 / Ironwood decoder: assertions A2, A3 and A5.
 *
 * EVERY FIXTURE HERE GOES THROUGH THE REAL BOUNDARY SCHEMA, and that is the one
 * methodological thing this file gets right. `rpc-casing.test.ts` established
 * the rule after `expiryheight` spent three revolutions invisible: a fixture
 * written as a TypeScript object literal agrees with whatever the author typed,
 * so it can only ever confirm the author. Parsing through
 * `rpcTransactionSchema` / `rpcBlockSchema` at least proves the fixture is a
 * shape this project's own boundary accepts.
 *
 * IT DOES NOT PROVE THE SHAPE IS ZEBRA'S, AND THAT LIMIT IS THE HONEST HEADLINE
 * OF THIS WHOLE FILE. Nothing in this repository has ever seen a real Ironwood
 * bundle: there is no captured v6 transaction anywhere in the tree, the JSON
 * beside this file was generated by this session, and the `ironwood` field name
 * it uses is the same inference the schema uses. So A2's evidence is
 * SELF-REFERENTIAL - it will pass whether or not Zebra calls the field
 * `ironwood` - and saying so is worth more than the assertion. HANDOFF-10's
 * captured mainnet block is what settles it; until then the decoder's own alarm
 * (a finding on a v6 carrying no `ironwood` key) is what would announce a wrong
 * guess against a real node.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import { rpcBlockSchema, rpcTransactionSchema } from "@zcashreveal/zebra-rpc";
import type { RpcBlock } from "@zcashreveal/zebra-rpc";
import { asHex, type Hex, type RpcTransaction } from "@zcashreveal/types";

import { boundaryDeltasOf, decodeBlock } from "../block-decoder.js";
import { decodeIronwoodBundle, hasContiguousPositions } from "../ironwood.js";
import {
  canonicalOrchardProofBytes,
  orchardProofSizeViolation,
} from "../orchard.js";
import { dispatchByVersion, MAX_SUPPORTED_TX_VERSION } from "../v6.js";
import { analyze, type AnalyzeContext } from "../leak-analyzer.js";
import type { AnchorRegistry } from "../anchor-depth.js";
import { NU6_3_ACTIVATION_MAINNET } from "../activation-heights.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(
  HERE,
  "../../../test/fixtures/blocks/synthetic-v6-ironwood-3430000.json",
);

/**
 * The fixture, parsed through the real `getblock` boundary.
 *
 * NOT `JSON.parse(...) as RpcBlock`. The cast form is what
 * `block-decoder.test.ts`'s real-fixture suite uses, and it is exactly as
 * strong as the author's typing; going through the schema at least makes the
 * fixture answer to the same validation a node's response does, including the
 * hex patterns, the integer checks and the zatoshi guards.
 */
function loadFixture(): RpcBlock {
  const raw: unknown = JSON.parse(readFileSync(FIXTURE, "utf8"));
  const parsed = rpcBlockSchema.parse(raw);
  const tx: RpcTransaction[] = [];
  for (const entry of parsed.tx) {
    if (typeof entry === "string") throw new Error("fixture must be verbosity 2");
    tx.push(entry);
  }
  return {
    hash: parsed.hash,
    height: parsed.height as number,
    time: parsed.time as number,
    tx,
    ...(parsed.finalsaplingroot === undefined ? {} : { finalsaplingroot: parsed.finalsaplingroot }),
    ...(parsed.finalorchardroot === undefined ? {} : { finalorchardroot: parsed.finalorchardroot }),
    ...(parsed.finalironwoodroot === undefined ? {} : { finalironwoodroot: parsed.finalironwoodroot }),
  };
}

const ZEC = 100_000_000n;
const FEE = 10_000n;

function offlineRegistry(): AnchorRegistry {
  return { getHeightForAnchor: () => Promise.resolve(null) } as unknown as AnchorRegistry;
}

function context(): AnalyzeContext {
  return {
    tipHeight: 3_430_000,
    seenAt: 1_785_000_000,
    anchorRegistry: offlineRegistry(),
    recentAnchorThreshold: 100,
  };
}

describe("the fixture is a v6 block in the region the assertions are about", () => {
  it("sits at or above NU6.3, so Ironwood exists and Orchard is exit-only here", () => {
    // THE GUARD THAT STOPS EVERY OTHER ASSERTION IN THIS FILE FROM BEING ABOUT
    // A CHAIN THAT DOES NOT EXIST. The synthetic block builder that predates
    // this file defaults to height 1,700,000 - 1.7 million blocks below NU6.3 -
    // so a fixture copied from it would exercise none of the region v6 and
    // Ironwood live in, while the transcript said the four-pool replay was
    // verified.
    const block = loadFixture();
    expect(block.height).toBeGreaterThanOrEqual(NU6_3_ACTIVATION_MAINNET);
    expect(block.tx.some((t) => t.version === 6)).toBe(true);
  });

  it("survives the real boundary schema rather than only the interface", () => {
    // If the fixture were shaped wrongly - an action missing `cmx`, a balance
    // as a float, hex with an `0x` - this throws. That is a weaker guarantee
    // than a captured response and a stronger one than a cast.
    expect(() => loadFixture()).not.toThrow();
  });
});

describe("A2 - the v6 fixture yields Ironwood commitments with contiguous positions", () => {
  it("decodes every Ironwood bundle and every action index runs 0..n-1", () => {
    const decoded = decodeBlock(loadFixture());
    const withIronwood = decoded.txs.filter((t) => t.ironwoodActions.length > 0);

    // COVERAGE GUARD FIRST. Without it every assertion below is vacuously true
    // on a fixture whose Ironwood bundles were spelled differently from what
    // the decoder reads - a loop over an empty array passes everything.
    expect(withIronwood.length).toBeGreaterThan(0);

    for (const tx of withIronwood) {
      expect(hasContiguousPositions(tx.ironwoodActions)).toBe(true);
      expect(tx.ironwoodActions.map((a) => a.index)).toEqual(
        tx.ironwoodActions.map((_a, i) => i),
      );
      // The pool literal is what keeps an Ironwood action out of an Orchard
      // array at compile time, so it is worth asserting at run time too.
      expect(new Set(tx.ironwoodActions.map((a) => a.pool))).toEqual(new Set(["ironwood"]));
    }

    // The intra-pool transfer carries two actions, so contiguity is a real test
    // here rather than the trivial single-element case.
    expect(Math.max(...withIronwood.map((t) => t.ironwoodActions.length))).toBeGreaterThan(1);
  });

  it("carries the fixture's own value balance, per transaction and in the deltas", () => {
    const block = loadFixture();
    const decoded = decodeBlock(block);

    // Read the expected values out of the RAW fixture rather than restating
    // them, so the assertion cannot drift from the file it is about.
    for (const [i, raw] of block.tx.entries()) {
      const expected = BigInt(raw.ironwood?.valueBalanceZat ?? 0);
      expect(decoded.txs[i]?.ironwoodValueBalanceZat).toBe(expected);
    }

    // And the same values reach `boundaryDeltasOf`, which is the projection a
    // PoolState replay consumes. A pool that did not move produces no delta.
    const ironwoodDeltas = boundaryDeltasOf(decoded).filter((d) => d.pool === "ironwood");
    expect(ironwoodDeltas).toHaveLength(2);
    expect(ironwoodDeltas.map((d) => d.deltaZat)).toEqual([
      -(500n * ZEC - FEE),
      -(100n * ZEC - FEE),
    ]);
  });

  it("FAIL SIDE: a block with no Ironwood bundles produces no Ironwood surface at all", () => {
    // The discriminating half. Strip the bundles and every assertion above
    // fails: the actions are gone, the deltas are gone, and the block-level
    // anchor is not emitted. Without this the assertions above would pass on a
    // decoder that fabricated an empty Ironwood surface for every block.
    const block = loadFixture();
    const stripped: RpcBlock = {
      ...block,
      tx: block.tx.map((t) => {
        const { ironwood: _dropped, ...rest } = t;
        return rest;
      }),
    };
    const decoded = decodeBlock(stripped);

    expect(decoded.txs.every((t) => t.ironwoodActions.length === 0)).toBe(true);
    expect(boundaryDeltasOf(decoded).filter((d) => d.pool === "ironwood")).toHaveLength(0);
    expect(decoded.ironwoodAnchor).toBeNull();
    // And the absence is reported as an absence rather than as "the pool did
    // not move": no commitments were appended, so there is nothing to flag.
    expect(decoded.ironwoodRootUnobserved).toBe(false);
  });

  it("a block that adds Ironwood commitments with no root says so, instead of reading as empty", () => {
    // THE ALARM ON THE INFERRED FIELD NAME. `finalironwoodroot` is guessed by
    // analogy from its two siblings; if the guess is wrong the anchor is null
    // on every block forever, and null is indistinguishable from "this block
    // added no Ironwood commitments". The flag separates the two.
    const block = loadFixture();
    const { finalironwoodroot: _dropped, ...withoutRoot } = block;
    const decoded = decodeBlock(withoutRoot);

    expect(decoded.ironwoodAnchor).toBeNull();
    expect(decoded.ironwoodRootUnobserved).toBe(true);

    // Pass state: with the root present the anchor is emitted and the flag is
    // down, so the flag is not simply always true.
    const withRoot = decodeBlock(block);
    expect(withRoot.ironwoodAnchor?.root).toBe(block.finalironwoodroot);
    expect(withRoot.ironwoodRootUnobserved).toBe(false);
  });
});

describe("A3 - an unmodelled version becomes UNSUPPORTED_TX and never a throw", () => {
  /** The fixture's 500 ZEC migration, straight out of the file. */
  function orchardToIronwoodFixtureTx(): RpcTransaction {
    const block = loadFixture();
    const migration = block.tx.find(
      (t) => t.version === 6 && BigInt(t.orchard?.valueBalanceZat ?? 0) === 500n * ZEC,
    );
    if (migration === undefined) throw new Error("fixture has no 500 ZEC migration");
    return migration;
  }

  /** The same transaction with only the version changed, so nothing else differs. */
  function versionSeven(): RpcTransaction {
    return { ...orchardToIronwoodFixtureTx(), version: 7 };
  }

  /** A bare transaction at a chosen version, with no bundles at all. */
  function txn(version: number): RpcTransaction {
    return {
      txid: asHex("cd".repeat(32)),
      version,
      locktime: 0,
      vin: [],
      vout: [],
    };
  }

  it("PASS: version 7 classifies UNSUPPORTED_TX, measures nothing, and does not throw", async () => {
    const report = await analyze(versionSeven(), context());

    expect(report.leakClass).toBe("UNSUPPORTED_TX");
    expect(report.unsupported?.version).toBe(7);
    expect(report.unsupported?.reason).toContain("outside the range this decoder models");
    // The raw field names are logged, which is the one artefact a later handoff
    // implementing v7 cannot reconstruct. Keys only - never values.
    expect(report.unsupported?.rawFieldNames).toContain("orchard");
    expect(report.unsupported?.rawFieldNames).toContain("ironwood");

    // NOTHING WAS MEASURED, and the report says so in the shapes that already
    // mean it rather than only in the flag.
    expect(report.valueFlow.perPoolZat).toEqual([]);
    expect(report.valueFlow.direction).toBe("NONE");
    expect(report.bundle.orchardActions).toEqual([]);
    expect(report.bundle.ironwoodActions).toEqual([]);
    expect(report.fingerprint.feeZat).toBeNull();
    expect(report.overallSeverity).toBe("INFO");
  });

  it("FAIL SIDE: the SAME BYTES read as v6 produce the confident answer the guard withholds", async () => {
    // THIS ASSERTION REPLACES ONE THAT DID NOT DISCRIMINATE, AND THE
    // REPLACEMENT IS THE INTERESTING PART. The first version asserted that
    // `decodeIronwoodBundle({ valueBalanceZat: undefined })` throws, and
    // justified it as "what the analyser would do with the guard gone". That
    // was false: with the guard gone the analyser would read the FIXTURE's
    // well-formed bundle, not a malformed one, so the assertion proved only
    // that `BigInt(undefined)` throws - a property of BigInt. A fail-side probe
    // that cannot fail for the reason it names is a finding in this project
    // (LEDGER-05 fold 7), and a gate round raised it as one.
    //
    // What removing the guard actually produces is worse than a throw and is
    // what the guard exists for: a CONFIDENT FABRICATED MEASUREMENT. A test
    // cannot delete production code, so the same fabrication is shown the only
    // honest way - by feeding the identical transaction in under a version the
    // decoder DOES model. Every number below is what an unguarded v7 would have
    // published about bytes nobody here understands.
    const asV6 = await analyze(orchardToIronwoodFixtureTx(), context());
    expect(asV6.leakClass).toBe("MIGRATION_O2I");
    expect(asV6.valueFlow.orchardValueBalanceZat).toBe(500n * ZEC);
    expect(asV6.valueFlow.ironwoodValueBalanceZat).toBe(-(500n * ZEC - FEE));
    expect(asV6.fingerprint.feeZat).not.toBeNull();
    expect(asV6.overallSeverity).not.toBe("INFO");

    // The identical transaction at version 7: every one of those measurements
    // is withheld, and the report says why rather than saying zero.
    const asV7 = await analyze(versionSeven(), context());
    expect(asV7.leakClass).toBe("UNSUPPORTED_TX");
    expect(asV7.valueFlow.orchardValueBalanceZat).toBe(0n);
    expect(asV7.valueFlow.ironwoodValueBalanceZat).toBe(0n);
    expect(asV7.fingerprint.feeZat).toBeNull();
    expect(asV7.unsupported).toBeDefined();

    // AND THE GUARD IS WHAT SEPARATES THEM, not the transaction's contents.
    // `dispatchByVersion` is the only thing that differs between the two calls.
    expect(dispatchByVersion(orchardToIronwoodFixtureTx()).kind).toBe("SUPPORTED");
    expect(dispatchByVersion(versionSeven()).kind).toBe("UNSUPPORTED");
  });

  it("the guard runs BEFORE any field is interpreted, so an unreadable bundle cannot throw", async () => {
    // The second half of what the guard buys, and the half a throw does
    // demonstrate. `decodeIronwoodBundle` on a bundle whose value balance
    // cannot be converted throws - that is real, and it is what an unmodelled
    // format's bundle could look like.
    const malformed = { actions: [], valueBalanceZat: undefined as unknown as number };
    expect(() => decodeIronwoodBundle(malformed)).toThrow(TypeError);

    // On a v6 the guard does not apply, because v6 IS modelled - so the same
    // malformed bundle reaches the decoder and `analyze()` itself throws. This
    // is the analyser throwing through the real path, which the old assertion
    // claimed and did not show.
    await expect(
      analyze({ ...orchardToIronwoodFixtureTx(), ironwood: malformed }, context()),
    ).rejects.toThrow(TypeError);

    // On a v7 the same bundle is refused before it is read, and nothing throws.
    await expect(
      analyze({ ...versionSeven(), ironwood: malformed }, context()),
    ).resolves.toMatchObject({ leakClass: "UNSUPPORTED_TX" });
  });

  it("a v5 or v6 carrying JoinSplits is refused, which is the third of the three rules", async () => {
    // v6.ts presents three refusals and two of them were covered; deleting this
    // one changed no test. JoinSplits were removed by the v5 format (ZIP 225)
    // and v6 did not bring them back, so a v5 or v6 carrying one contradicts
    // its own format and cannot be classified.
    for (const version of [5, 6]) {
      const tx: RpcTransaction = {
        ...txn(version),
        vjoinsplit: [{ vpub_oldZat: 0, vpub_newZat: 100_000 }],
      };
      const dispatch = dispatchByVersion(tx);
      expect(dispatch.kind, `v${String(version)}`).toBe("UNSUPPORTED");
      const report = await analyze(tx, context());
      expect(report.leakClass).toBe("UNSUPPORTED_TX");
      expect(report.unsupported?.reason).toContain("JoinSplits");
    }

    // FAIL SIDE: the same JoinSplit on a v4 is ordinary Sprout traffic and is
    // classified normally, so the rule is about the VERSION and not about
    // JoinSplits being unwelcome.
    const v4 = await analyze(
      { ...txn(4), vjoinsplit: [{ vpub_oldZat: 0, vpub_newZat: 100_000 }] },
      context(),
    );
    expect(v4.leakClass).not.toBe("UNSUPPORTED_TX");
    expect(v4.valueFlow.sproutValueBalanceZat).toBe(100_000n);
  });

  it("IRONWOOD_FIELD_ABSENT fires on a v6 with no ironwood key, and on nothing else", async () => {
    // THE ONE ALARM THE WHOLE IRONWOOD DECODER RESTS ON, AND IT HAD NO TEST.
    // Three docblocks - here, in `schemas.ts` and in `fee.ts` - argue that a
    // wrong guess at the `ironwood` field name would be caught because this
    // finding would start firing on every v6 transaction. Nothing pinned it, so
    // it could have been deleted in any later edit with the suite green, and
    // the argument those three docblocks make would have quietly become false.
    //
    // It is an all-or-nothing alarm by design: under the belief about the wire
    // it fires on almost nothing, and if the belief is wrong it fires on
    // everything. Both polarities are therefore the test.
    const withoutKey = await analyze(txn(6), context());
    expect(withoutKey.findings.map((f) => f.code)).toContain("IRONWOOD_FIELD_ABSENT");
    // It is a fact about the RESPONSE on a report that WAS decoded, so it must
    // not be confused with the abstention path: the class is a real class and
    // there is no `unsupported` object.
    expect(withoutKey.leakClass).not.toBe("UNSUPPORTED_TX");
    expect(withoutKey.unsupported).toBeUndefined();
    expect(withoutKey.findings.map((f) => f.code)).not.toContain("UNSUPPORTED_TX_SHAPE");
    expect(withoutKey.findings.find((f) => f.code === "IRONWOOD_FIELD_ABSENT")?.message).toContain(
      "false zero",
    );

    // FAIL SIDE 1: a v6 that DOES carry the key, even an empty bundle, is
    // silent. If it were not, the alarm would fire on every v6 on the chain and
    // mean nothing.
    const withEmptyKey = await analyze(
      { ...txn(6), ironwood: { actions: [], valueBalanceZat: 0 } },
      context(),
    );
    expect(withEmptyKey.findings.map((f) => f.code)).not.toContain("IRONWOOD_FIELD_ABSENT");

    // FAIL SIDE 2: a v5 without the key is silent too, because v5 cannot carry
    // an Ironwood bundle and its absence there says nothing about the wire.
    const v5 = await analyze(txn(5), context());
    expect(v5.findings.map((f) => f.code)).not.toContain("IRONWOOD_FIELD_ABSENT");
  });

  it("a v4 carrying Ironwood actions is refused too, and names the contradiction", async () => {
    // Not an unknown version - a known one whose contents contradict its own
    // format. Consensus cannot produce it, so seeing it means this decoder has
    // misread the response; refusing to classify is the honest answer and
    // crashing is not.
    const block = loadFixture();
    const migration = block.tx.find((t) => t.version === 6);
    const report = await analyze({ ...(migration as RpcTransaction), version: 4 }, context());

    expect(report.leakClass).toBe("UNSUPPORTED_TX");
    expect(report.unsupported?.reason).toContain("Ironwood bundle exists only from v6");
  });

  it("every version the decoder DOES model is dispatched as supported", () => {
    // The other polarity for the dispatcher itself: if this ever went red for a
    // version in range, the refusal above would be firing on ordinary traffic.
    for (let v = 1; v <= MAX_SUPPORTED_TX_VERSION; v += 1) {
      const tx: RpcTransaction = { txid: asHex("ab") as Hex, version: v, locktime: 0, vin: [], vout: [] };
      expect(dispatchByVersion(tx).kind, `v${v}`).toBe("SUPPORTED");
    }
    expect(dispatchByVersion({
      txid: asHex("ab") as Hex,
      version: MAX_SUPPORTED_TX_VERSION + 1,
      locktime: 0,
      vin: [],
      vout: [],
    }).kind).toBe("UNSUPPORTED");
  });
});

describe("A5 - ZIP 257's canonical Orchard proof length", () => {
  const NU6_2 = 3_364_600;

  it("PASS: the fixture's proofs are canonical, so no finding is raised", async () => {
    const block = loadFixture();
    const migration = block.tx.find((t) => t.version === 6 && (t.orchard?.actions.length ?? 0) > 0);
    expect(migration).toBeDefined();

    // The fixture was built to the rule, so this is a check on the arithmetic
    // as much as on the file: 2720 + 2272 x 1 = 4992 bytes, 9984 hex characters.
    expect((migration?.orchard?.proof?.length ?? 0) / 2).toBe(canonicalOrchardProofBytes(1));

    const report = await analyze(migration as RpcTransaction, context());
    expect(report.findings.map((f) => f.code)).not.toContain("PROOF_SIZE_NONCANONICAL");
  });

  it("FAIL: one byte short of canonical raises PROOF_SIZE_NONCANONICAL, and does not throw", async () => {
    // A5's own shape: 2720 + 2272 x 2 - 1 bytes on a two-action bundle.
    const shortByOne = orchardProofSizeViolation({
      proof: "ab".repeat(canonicalOrchardProofBytes(2) - 1),
      actionCount: 2,
      height: NU6_2,
      nu6_2ActivationHeight: NU6_2,
    });
    expect(shortByOne).toEqual({
      expectedBytes: canonicalOrchardProofBytes(2),
      actualBytes: canonicalOrchardProofBytes(2) - 1,
    });

    // And it reaches the report as a finding rather than an exception. A
    // consensus-valid chain cannot carry this, so a throw would present the
    // decoder's own error as a fault in the chain and stop the indexer.
    const block = loadFixture();
    const migration = block.tx.find((t) => t.version === 6 && (t.orchard?.actions.length ?? 0) > 0);
    const broken: RpcTransaction = {
      ...(migration as RpcTransaction),
      orchard: {
        ...(migration?.orchard as NonNullable<RpcTransaction["orchard"]>),
        proof: asHex("ab".repeat(canonicalOrchardProofBytes(1) - 1)),
      },
    };
    const report = await analyze(broken, context());
    expect(report.findings.map((f) => f.code)).toContain("PROOF_SIZE_NONCANONICAL");
    expect(report.leakClass).toBe("MIGRATION_O2I");
  });

  it("the correct length at the same height produces none, so the height is not doing the work", () => {
    expect(
      orchardProofSizeViolation({
        proof: "ab".repeat(canonicalOrchardProofBytes(2)),
        actionCount: 2,
        height: NU6_2,
        nu6_2ActivationHeight: NU6_2,
      }),
    ).toBeNull();
  });

  it("below NU6.2 the rule did not exist, so a short proof is not a finding", () => {
    // Measuring it there would be an anachronism rather than a finding. Every
    // length was legal before NU6.2 replaced the verifying key.
    //
    // (The wording deliberately avoids a colon followed by the word A6's grep
    // looks for. A6's literal check is a TEXT search over this directory, so a
    // comment can trip it - and a comment did, in the first draft of this file.
    // The assertion A6 is about is the TYPE, which eslint's no-explicit-any
    // enforces as an error across apps/indexer/src; the grep is a second,
    // cruder net, and it is kept satisfiable rather than argued with. Worth
    // knowing that the eslint rule is switched OFF for test files, so in this
    // directory the grep is the only net there is.)
    expect(
      orchardProofSizeViolation({
        proof: "ab".repeat(10),
        actionCount: 2,
        height: NU6_2 - 1,
        nu6_2ActivationHeight: NU6_2,
      }),
    ).toBeNull();
  });

  it("an absent proof is not a violation, because Zebra omits it", () => {
    // `skip_serializing_if = "Option::is_none"`, and the bundle key itself is
    // emitted even for transactions with no actions. Absence is the ordinary
    // case, not a broken length.
    expect(
      orchardProofSizeViolation({
        proof: undefined,
        actionCount: 2,
        height: NU6_2,
        nu6_2ActivationHeight: NU6_2,
      }),
    ).toBeNull();
  });

  it("the rule is Orchard's alone - an Ironwood proof of any length is unmeasured", async () => {
    // Ironwood reuses the corrected Orchard circuit, so applying the same
    // arithmetic to its proof is tempting. Nothing in this repository states an
    // Ironwood proof-length rule, and a plausible constant would be
    // indistinguishable to every later reader from a sourced one.
    const block = loadFixture();
    const migration = block.tx.find((t) => t.version === 6 && (t.ironwood?.actions.length ?? 0) > 0);
    const brokenIronwood: RpcTransaction = {
      ...(migration as RpcTransaction),
      ironwood: {
        ...(migration?.ironwood as NonNullable<RpcTransaction["ironwood"]>),
        proof: asHex("ab"),
      },
    };
    const report = await analyze(brokenIronwood, context());
    expect(report.findings.map((f) => f.code)).not.toContain("PROOF_SIZE_NONCANONICAL");
  });
});

describe("the boundary parses the fixture's transactions one at a time too", () => {
  it("each v6 transaction survives rpcTransactionSchema, ironwood bundle included", () => {
    const raw: unknown = JSON.parse(readFileSync(FIXTURE, "utf8"));
    const txs = (raw as { tx: unknown[] }).tx;
    const parsed = txs.map((t) => rpcTransactionSchema.parse(t));

    const v6 = parsed.filter((t) => t.version === 6);
    expect(v6.length).toBeGreaterThan(0);
    for (const tx of v6) {
      expect(tx.ironwood).toBeDefined();
      expect(typeof tx.ironwood?.valueBalanceZat).toBe("number");
    }
  });
});
